# Generated by Django 3.2.16 on 2022-12-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='abc@example.com', max_length=255)),
                ('alias', models.CharField(default='example', max_length=255)),
            ],
        ),
    ]
