# Generated by Django 3.2.16 on 2022-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20221205_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='alias',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
